name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # This runs the action every hour
  workflow_dispatch: # This allows you to run the action manually from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: kunal04sinha/cloudarops # Update this to the original repository
          ref: main # Update this to the default branch of the original repository

      - name: Checkout the fork
        run: |
          git remote add fork https://github.com/${{ github.repository }}
          git fetch fork
          git checkout fork/main # Update this to the default branch of your fork
          git merge --no-edit origin/main # Update this to the default branch of the original repository

      - name: Push changes
        run: |
          git push fork main # Update this to the default branch of your fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
